"use client";
import Link from "next/link";
import { useState } from "react";
import { useLocale } from "./LocaleProvider";

export function QuickCalculator() {
  const {t}=useLocale();
  const [area, setArea] = useState(45); const [distance, setDistance] = useState(25); const [from, setFrom] = useState(1); const [to, setTo] = useState(2); const [fromLift, setFromLift] = useState(true); const [toLift, setToLift] = useState(false); const [price, setPrice] = useState<{min:number;max:number} | null>(null); const [loading, setLoading] = useState(false);
  async function submit() { setLoading(true); const r = await fetch("/api/calculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ movingType: "apartment", area, distance, originFloor: from, destinationFloor: to, originElevator: fromLift, destinationElevator: toLift, services: [] }) }); if (r.ok) setPrice(await r.json()); setLoading(false); }
  return <section id="rechner" className="quick-wrap"><div className="shell"><div className="calculator-card"><div className="calc-title"><span className="eyebrow">{t("quickCalc")}</span><h2>{t("whatCost")}</h2><p>{t("quickLead")}</p></div><div className="calc-fields"><label>{t("area")} <span><input type="number" min="1" value={area} onChange={e => setArea(Number(e.target.value))}/> m²</span></label><label>{t("distance")} <span><input type="number" min="0" value={distance} onChange={e => setDistance(Number(e.target.value))}/> km</span></label><label>{t("originFloor")} <span><select value={from} onChange={e => setFrom(Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><button className={fromLift ? "toggle on" : "toggle"} onClick={() => setFromLift(!fromLift)} type="button">{t("elevator")}</button></span></label><label>{t("destinationFloor")} <span><select value={to} onChange={e => setTo(Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><button className={toLift ? "toggle on" : "toggle"} onClick={() => setToLift(!toLift)} type="button">{t("elevator")}</button></span></label></div><div className="calc-action"><button className="button" onClick={submit} disabled={loading}>{loading ? t("calculating") : t("priceCalc")}</button>{price && <div className="quick-result"><small>{t("estimate")}</small><strong>{price.min}–{price.max} €</strong><Link href="/calculator">{t("addDetails")}</Link></div>}</div></div></div></section>;
}
