"use client";
import { useState } from "react";
import { pricing, type MovingType, type ServiceKey } from "@/config/pricing";
import { Icon } from "./Icon";
import { useLocale } from "./LocaleProvider";

const serviceKeys = Object.keys(pricing.services) as ServiceKey[];
const copy = {
 de:{steps:["Umzug","Größe","Route","Etagen","Extras","Termin","Preis"],types:{apartment:"Wohnung",house:"Haus",office:"Büro",furniture:"Möbelstück",other:"Anderes"},s1:"Was möchten Sie umziehen?",s1p:"Wählen Sie die Variante, die am besten zu Ihrem Vorhaben passt.",s2:"Wie groß ist der Umzug?",s2p:"Eine grobe Angabe genügt für Ihren ersten Preisrahmen.",small:"Kleines Studio",large:"Große Wohnung",s3:"Wo startet Ihre Route?",s3p:"Stadt und Entfernung reichen für die unverbindliche Kalkulation.",from:"Von",to:"Nach",example1:"z. B. Berlin",example2:"z. B. Potsdam",distance:"Entfernung",s4:"Wie gut sind die Etagen erreichbar?",origin:"Auszugsadresse",destination:"Einzugsadresse",floor:"Etage",ground:"Erdgeschoss",elevator:"Aufzug vorhanden",yes:"Ja",no:"Nein",s5:"Was dürfen wir Ihnen abnehmen?",s5p:"Sie können diese Auswahl später jederzeit mit uns besprechen.",s6:"Wann soll es losgehen?",s6p:"Eine ungefähre Angabe hilft uns bei der späteren Planung.",date:"Wunschtermin",open:"Termin noch offen",estimate:"Ihr Richtwert",summary:"Ihre Umzugskalkulation",calcText:"Wir berechnen Ihren Preis direkt aus Ihren Angaben.",show:"Jetzt Preis anzeigen",range:"Voraussichtlicher Preisrahmen",id:"Berechnungsnummer",base:"Grundpreis",sizeRoute:"Größe & Strecke",floorsExtras:"Etagen & Extras",fine:"Dieser Betrag ist unverbindlich. Die genaue Summe bestätigen wir nach einem kurzen Gespräch.",send:"Anfrage senden",back:"← Zurück",next:"Weiter",step:"Schritt",calc:"Wird berechnet…"},
 en:{steps:["Move","Size","Route","Floors","Extras","Date","Price"],types:{apartment:"Apartment",house:"House",office:"Office",furniture:"Furniture",other:"Other"},s1:"What are you moving?",s1p:"Choose the option that best matches your move.",s2:"How large is the move?",s2p:"A rough estimate is enough for the first price range.",small:"Small studio",large:"Large apartment",s3:"Where does your route start?",s3p:"City and distance are enough for the initial estimate.",from:"From",to:"To",example1:"e.g. Berlin",example2:"e.g. Potsdam",distance:"Distance",s4:"How accessible are the floors?",origin:"Pickup address",destination:"Destination address",floor:"Floor",ground:"Ground floor",elevator:"Elevator available",yes:"Yes",no:"No",s5:"What can we handle for you?",s5p:"You can always discuss these options with us later.",s6:"When should the move happen?",s6p:"An approximate date helps with planning.",date:"Preferred date",open:"Date not decided yet",estimate:"Your estimate",summary:"Your moving estimate",calcText:"We calculate the price directly from your information.",show:"Show price",range:"Estimated price range",id:"Estimate ID",base:"Base price",sizeRoute:"Size & distance",floorsExtras:"Floors & extras",fine:"This amount is non-binding. We confirm the exact total after a short conversation.",send:"Send enquiry",back:"← Back",next:"Next",step:"Step",calc:"Calculating…"},
 uk:{steps:["Переїзд","Розмір","Маршрут","Поверхи","Додатково","Дата","Ціна"],types:{apartment:"Квартира",house:"Будинок",office:"Офіс",furniture:"Меблі",other:"Інше"},s1:"Що потрібно перевезти?",s1p:"Оберіть варіант, який найкраще відповідає вашому переїзду.",s2:"Який обсяг переїзду?",s2p:"Для першого розрахунку достатньо приблизної площі.",small:"Невелика студія",large:"Велика квартира",s3:"Звідки починається маршрут?",s3p:"Міста та відстані достатньо для попереднього розрахунку.",from:"Звідки",to:"Куди",example1:"напр. Берлін",example2:"напр. Потсдам",distance:"Відстань",s4:"Наскільки доступні поверхи?",origin:"Адреса виїзду",destination:"Адреса прибуття",floor:"Поверх",ground:"Перший поверх",elevator:"Є ліфт",yes:"Так",no:"Ні",s5:"Що ми можемо взяти на себе?",s5p:"Цей вибір можна буде змінити пізніше.",s6:"Коли планується переїзд?",s6p:"Приблизна дата допоможе нам із плануванням.",date:"Бажана дата",open:"Дата ще не визначена",estimate:"Орієнтовна вартість",summary:"Розрахунок переїзду",calcText:"Ми розрахуємо ціну безпосередньо за вашими даними.",show:"Показати ціну",range:"Орієнтовний діапазон",id:"Номер розрахунку",base:"Базова ціна",sizeRoute:"Розмір і відстань",floorsExtras:"Поверхи та послуги",fine:"Ця сума є орієнтовною. Точну вартість ми підтвердимо після короткого уточнення.",send:"Надіслати заявку",back:"← Назад",next:"Далі",step:"Крок",calc:"Розраховуємо…"},
 ru:{steps:["Переезд","Размер","Маршрут","Этажи","Дополнительно","Дата","Цена"],types:{apartment:"Квартира",house:"Дом",office:"Офис",furniture:"Мебель",other:"Другое"},s1:"Что нужно перевезти?",s1p:"Выберите вариант, который лучше всего подходит вашему переезду.",s2:"Какой объём переезда?",s2p:"Для первого расчёта достаточно примерной площади.",small:"Небольшая студия",large:"Большая квартира",s3:"Откуда начинается маршрут?",s3p:"Города и расстояния достаточно для предварительного расчёта.",from:"Откуда",to:"Куда",example1:"например, Берлин",example2:"например, Потсдам",distance:"Расстояние",s4:"Насколько доступны этажи?",origin:"Адрес отправления",destination:"Адрес назначения",floor:"Этаж",ground:"Первый этаж",elevator:"Есть лифт",yes:"Да",no:"Нет",s5:"Что мы можем взять на себя?",s5p:"Этот выбор можно будет изменить позже.",s6:"Когда планируется переезд?",s6p:"Примерная дата поможет нам с планированием.",date:"Желаемая дата",open:"Дата пока не определена",estimate:"Ориентировочная стоимость",summary:"Расчёт переезда",calcText:"Мы рассчитаем цену напрямую по вашим данным.",show:"Показать цену",range:"Ориентировочный диапазон",id:"Номер расчёта",base:"Базовая цена",sizeRoute:"Размер и расстояние",floorsExtras:"Этажи и услуги",fine:"Эта сумма ориентировочная. Точную стоимость мы подтвердим после короткого уточнения.",send:"Отправить заявку",back:"← Назад",next:"Далее",step:"Шаг",calc:"Рассчитываем…"}
} as const;

const icons:Record<MovingType,"building"|"truck"|"layers"|"sofa"|"box">={apartment:"building",house:"truck",office:"layers",furniture:"sofa",other:"box"};
export function FullCalculator() {
 const {locale}=useLocale(); const c=copy[locale];
 const types=(Object.keys(icons) as MovingType[]).map(key=>({key,label:c.types[key],icon:icons[key]}));
 const [step,setStep] = useState(1); const [data,setData] = useState({ movingType:"apartment" as MovingType, area:45, distance:25, originFloor:1, destinationFloor:2, originElevator:true, destinationElevator:false, services:[] as ServiceKey[], date:"", cityFrom:"", cityTo:"" }); const [result,setResult] = useState<{min:number;max:number;id:string;breakdown:{base:number;area:number;distance:number;stairs:number;extras:number}} | null>(null); const [busy,setBusy]=useState(false);
 const update = <K extends keyof typeof data>(key: K, value: (typeof data)[K]) => setData(d => ({...d,[key]:value}));
 const toggle = (key:ServiceKey) => update("services", data.services.includes(key) ? data.services.filter(s=>s!==key) : [...data.services,key]);
 const calculate = async () => { setBusy(true); const r=await fetch("/api/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}); if(r.ok) setResult(await r.json()); setBusy(false); };
 const canNext = step !== 2 || data.area > 0;
 return <div className="full-calculator"><div className="stepper">{c.steps.map((label,i)=><div className={i+1===step?"active":i+1<step?"done":""} key={label}><i>{i+1<step?<Icon name="check" size={13}/>:i+1}</i><span>{label}</span></div>)}</div><div className="step-content">
 {step===1 && <><span className="eyebrow">{c.step} 1 / 7</span><h2>{c.s1}</h2><p className="subcopy">{c.s1p}</p><div className="type-grid">{types.map(t=><button className={data.movingType===t.key?"type-card selected":"type-card"} onClick={()=>update("movingType",t.key)} key={t.key}><Icon name={t.icon} size={29}/><span>{t.label}</span><i><Icon name="check" size={13}/></i></button>)}</div></>}
 {step===2 && <><span className="eyebrow">{c.step} 2 / 7</span><h2>{c.s2}</h2><p className="subcopy">{c.s2p}</p><div className="range-row"><input aria-label="area" type="range" min="10" max="200" step="5" value={data.area} onChange={e=>update("area",Number(e.target.value))}/><strong>{data.area} <small>m²</small></strong></div><div className="range-label"><span>{c.small}</span><span>{c.large}</span></div></>}
 {step===3 && <><span className="eyebrow">{c.step} 3 / 7</span><h2>{c.s3}</h2><p className="subcopy">{c.s3p}</p><div className="route-grid"><label>{c.from}<input placeholder={c.example1} value={data.cityFrom} onChange={e=>update("cityFrom",e.target.value)}/></label><label>{c.to}<input placeholder={c.example2} value={data.cityTo} onChange={e=>update("cityTo",e.target.value)}/></label><label>{c.distance}<input type="number" min="0" value={data.distance} onChange={e=>update("distance",Number(e.target.value))}/><small>km</small></label></div></>}
 {step===4 && <><span className="eyebrow">{c.step} 4 / 7</span><h2>{c.s4}</h2><div className="floor-grid">{[[c.origin,"originFloor","originElevator"],[c.destination,"destinationFloor","destinationElevator"]].map(([label,floor,lift])=><div className="floor-card" key={label}><h3>{label}</h3><label>{c.floor}<select value={data[floor as "originFloor"|"destinationFloor"]} onChange={e=>update(floor as "originFloor"|"destinationFloor",Number(e.target.value))}>{Array.from({length:11},(_,n)=><option value={n} key={n}>{n === 0 ? c.ground : `${n}`}</option>)}</select></label><button type="button" onClick={()=>update(lift as "originElevator"|"destinationElevator",!data[lift as "originElevator"|"destinationElevator"])} className={data[lift as "originElevator"|"destinationElevator"]?"lift-choice active":"lift-choice"}>{c.elevator} <span>{data[lift as "originElevator"|"destinationElevator"]?c.yes:c.no}</span></button></div>)}</div></>}
 {step===5 && <><span className="eyebrow">{c.step} 5 / 7</span><h2>{c.s5}</h2><p className="subcopy">{c.s5p}</p><div className="service-list">{serviceKeys.map(key=><button key={key} onClick={()=>toggle(key)} className={data.services.includes(key)?"service-check checked":"service-check"}><i>{data.services.includes(key)&&<Icon name="check" size={15}/>}</i><span>{pricing.services[key].label}</span><small>€ {pricing.services[key].price}+</small></button>)}</div></>}
 {step===6 && <><span className="eyebrow">{c.step} 6 / 7</span><h2>{c.s6}</h2><p className="subcopy">{c.s6p}</p><div className="date-choice"><label>{c.date}<input type="date" min={new Date().toISOString().slice(0,10)} value={data.date} onChange={e=>update("date",e.target.value)}/></label><button onClick={()=>update("date","")} className={!data.date?"selected-date":""}>{c.open}</button></div></>}
 {step===7 && <><span className="eyebrow">{c.estimate}</span><h2>{c.summary}</h2>{!result ? <div className="ready-to-calc"><Icon name="shield" size={28}/><p>{c.calcText}</p><button className="button" onClick={calculate} disabled={busy}>{busy?c.calc:c.show}<Icon name="arrow" size={17}/></button></div> : <div className="price-result"><div><small>{c.range}</small><strong>{result.min}–{result.max} €</strong><p>{c.id}: <b>{result.id}</b></p></div><dl><div><dt>{c.base}</dt><dd>{result.breakdown.base} €</dd></div><div><dt>{c.sizeRoute}</dt><dd>{result.breakdown.area + result.breakdown.distance} €</dd></div><div><dt>{c.floorsExtras}</dt><dd>{result.breakdown.stairs + result.breakdown.extras} €</dd></div></dl><p className="fineprint">{c.fine}</p><a className="button" href="#anfrage">{c.send} <Icon name="arrow" size={17}/></a></div>}</>}
 </div><div className="step-nav"><button className="back" onClick={()=>setStep(s=>Math.max(1,s-1))} disabled={step===1}>{c.back}</button>{step<7 && <button className="button" onClick={()=>setStep(s=>s+1)} disabled={!canNext}>{c.next} <Icon name="arrow" size={17}/></button>}</div></div>;
}
